name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Nodejs Installation Check
      run: |
        node --version
        npm --version
    - name: Install Dependencies
      run: npm install
    - name: Start MongoDB
      run: |
        sudo apt-get install -y mongodb
        sudo service mongodb start
    - name: Run Tests
      run: npm test
