name: Publish to npm

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'

      # Step 3: Cache Node.js dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Ensure MongoDB service is ready
      - name: Wait for MongoDB
        run: |
          for i in {1..10}; do
            if mongosh --eval "db.runCommand({ ping: 1 })"; then
              echo "MongoDB is ready";
              exit 0;
            fi;
            echo "Waiting for MongoDB... (attempt $i/10)";
            sleep 5;
          done;
          echo "MongoDB failed to start";
          exit 1

      # Step 6: Run tests
      - name: Run tests
        env:
          MONGO_URI: mongodb://localhost:27017/poet-app
        run: npm test

      # Step 7: Build the project (if applicable)
      - name: Build the project
        run: npm run build

      # Step 8: Publish the package to npm
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

      # Step 9: Verify the publish step
      - name: Post publish verification
        run: |
          echo "Package published successfully."
          npm view poet-app version
